name: Pull Request (Opened)

on:
  pull_request:
    types: [opened]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Ensure SHA pinned actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@6ca5574367befbc9efdb2fa25978084159c5902d

  assign_author:
    name: Assign Author to the Pull Request
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Assign Author
      uses: technote-space/assign-author@v1.6.0


  pr-labeler:
    name: Label the PR based on the branch
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: PR Labeler
      uses: TimonVS/pr-labeler-action@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
