name: Pull Request (Opened)

on:
  pull_request:
    types: [opened]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Ensure SHA Pinned Actions
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v1.3.0
      with:
          allowlist: |
            aws-actions/
            docker/login-action

  assign_author:
    name: Assign Author to the Pull Request
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Assign Author
      uses: technote-space/assign-author@v1.3.1


  pr-labeler:
    name: Label the PR based on the branch
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: PR Labeler
      uses: TimonVS/pr-labeler-action@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
